#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure('2') do |config|
  config.vm.define 'node-01' do |node|
    node.vm.box = 'bento/ubuntu-18.04'
    node.vm.network :private_network, ip: '10.10.10.154'
    node.vm.hostname = 'node-01'
  end
end

